variables:
  YA_K8S_CLUSTER_NAME: "k8s-ya-cluster"
  YA_POSTGRESQL_CLUSTER_NAME: "postgresql-cluster"
  PSQL_DB: "yelbdatabase"
  PSQL_DBUSER: "yelbdbuser"
  PSQL_DBPASSWORD: "yelbdbpassword"

stages:
  - appserver_build
  - bd_init
  - test
  - redis_deploy
  - redis_delete

appserver_build:
  stage: appserver_build
  script:
    - docker logout
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID -f yelb-appserver/Dockerfile yelb-appserver/
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG.$CI_PIPELINE_ID
  tags:
    - shell
  when: manual

bd_init:
  stage: bd_init
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
  script:
    - export YA_POSTGRESQL_CLUSTER_ID=$(yc managed-postgresql cluster get --name $YA_POSTGRESQL_CLUSTER_NAME | head -n1 | awk '{print $2}')
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "CREATE TABLE restaurants (name char(30), count integer, PRIMARY KEY (name));"
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "INSERT INTO restaurants (name, count) VALUES ('outback', 0);"
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "INSERT INTO restaurants (name, count) VALUES ('bucadibeppo', 0);"
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "INSERT INTO restaurants (name, count) VALUES ('chipotle', 0);"
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "INSERT INTO restaurants (name, count) VALUES ('ihop', 0);"
  when: manual

test:
  stage: test
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
  script:
    - export YA_POSTGRESQL_CLUSTER_ID=$(yc managed-postgresql cluster get --name $YA_POSTGRESQL_CLUSTER_NAME | head -n1 | awk '{print $2}')
    - psql -a postgresql://${PSQL_DBUSER}:${PSQL_DBPASSWORD}@c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net:6432/${PSQL_DB}?sslmode=require -c "\dt"
  when: manual

redis_deploy:
  stage: redis_deploy
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
    - yc managed-kubernetes cluster get-credentials $YA_K8S_CLUSTER_NAME --external
  script: 
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm upgrade --install redis bitnami/redis -f helm/redis-values.yml
  when: manual

redis_delete:
  stage: redis_delete
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
    - yc managed-kubernetes cluster get-credentials $YA_K8S_CLUSTER_NAME --external
  script: helm delete redis
  when: manual