---
include:
  - local: '/ci-cd-files/.gitlab-ci-app.yml'

.var_appserver:
  variables:
    APP_NAME: "yelb-appserver"
    REPLICAS: "2"
    RACK_ENV: "custom"
    REDIS_SERVER_ENDPOINT: "redis-master.default.svc.cluster.local"

.var_ui:
  variables:
    APP_NAME: "yelb-ui"
    SITE_NAME: "s045841.site"
    REPLICAS: "2"

stages:
  - yaml_lint
  - helm_lint
  - build
  - test
  - push
  - deploy
  - delete

.yc_init:
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
    - yc managed-kubernetes cluster get-credentials $YA_K8S_CLUSTER_NAME --external
    - export YA_POSTGRESQL_CLUSTER_ID=$(yc managed-postgresql cluster get --name $YA_POSTGRESQL_CLUSTER_NAME | head -n1 | awk '{print $2}')
    - export YELB_DB_SERVER_ENDPOINT="c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net"

.build_command:
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:5
  script: docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID -f $APP_NAME/Dockerfile $APP_NAME/
  tags:
    - shell

test:
  stage: test
  script:
    - docker-compose up -d
    - sleep 10
    - curl localhost
    - docker-compose down -v
  tags:
    - shell

.push_command:
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:5
  before_script: docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script: docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID
  tags:
    - shell

yaml_lint:
  stage: yaml_lint
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:5
  script: yamllint -c yamllint.yaml .gitlab-ci.yml

.helm_lint:
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:5
  script: helm lint helm/$APP_NAME/

.helm_deploy:
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:5
  script: |
    kubectl create secret docker-registry temp-secret-$APP_NAME \
      --docker-server=$CI_REGISTRY \
      --docker-username=gitlab-ci-token \
      --docker-password=$CI_BUILD_TOKEN
    export PULL_SECRET=$(kubectl get secrets temp-secret-$APP_NAME -o jsonpath="{.data['\.dockerconfigjson']}")
    kubectl delete secrets temp-secret-$APP_NAME

    helm upgrade --install $APP_NAME helm/$APP_NAME/ --values helm/$APP_NAME/values.yaml \
      --set imagePullSecrets=$PULL_SECRET \
      --set image.repository=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID \
      --set replicaCount=${REPLICAS} \
      --set RACK_ENV=${RACK_ENV} \
      --set REDIS_SERVER_ENDPOINT=${REDIS_SERVER_ENDPOINT} \
      --set YELB_DB_SERVER_ENDPOINT=${YELB_DB_SERVER_ENDPOINT} \
      --set ingress.hosts[0].host=$SITE_NAME \
      --set ingress.tls[0].hosts[0]=$SITE_NAME

.helm_delete:
  script:
    - helm uninstall $APP_NAME
...
