include:
  - local: '/ci-cd-files/.gitlab-ci-app.yml'

variables:
  YA_K8S_CLUSTER_NAME: "k8s-ya-cluster"
  YA_POSTGRESQL_CLUSTER_NAME: "postgresql-cluster"
  PSQL_DB: "yelbdatabase"
  PSQL_DBUSER: "yelbdbuser"
  PSQL_DBPASSWORD: "yelbdbpassword"

.var_appserver:
  variables:
    APP_NAME: "yelb-appserver"
    REPLICAS: "2"
    RACK_ENV: "custom"
    REDIS_SERVER_ENDPOINT: "redis-master.default.svc.cluster.local"

.var_ui:
  variables:
    APP_NAME: "yelb-ui"
    REPLICAS: "2"

stages:
  - redis_deploy_db_init
  - redis_delete
  - build
  - deploy
  - delete

.yc_init:
  before_script:
    - yc config profile create profile1
    - yc config set cloud-id $YA_CLOUD_ID
    - yc config set folder-id $YA_FOLDER_ID
    - yc config set token $YA_TOKEN
    - yc managed-kubernetes cluster get-credentials $YA_K8S_CLUSTER_NAME --external
    - export YA_POSTGRESQL_CLUSTER_ID=$(yc managed-postgresql cluster get --name $YA_POSTGRESQL_CLUSTER_NAME | head -n1 | awk '{print $2}')
    - export YELB_DB_SERVER_ENDPOINT="c-${YA_POSTGRESQL_CLUSTER_ID}.rw.mdb.yandexcloud.net"
    - export YC_BALANCER_ID=$(yc load-balancer network-load-balancer list | grep EXTERNAL | awk '{print $2}')
    - export YC_BALANCER_IP=$(yc load-balancer network-load-balancer get --id $YC_BALANCER_ID | grep address | head -n1 | awk '{print $2}')

redis_deploy_db_init:
  stage: redis_deploy_db_init
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  extends:
    - .yc_init
  script:
    - chmod +x db_init.sh
    - ./db_init.sh
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm upgrade --install redis bitnami/redis -f helm/redis-values.yml
  when: manual

redis_delete:
  stage: redis_delete
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  extends:
    - .yc_init
  script: helm uninstall redis
  when: manual

.build_command:
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID -f $APP_NAME/Dockerfile $APP_NAME/
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID
  tags: 
    - shell
  when: manual

.helm_deploy: 
  image: s045841.gitlab.yandexcloud.net:5050/smix128/graduation_work/centos-tools:4
  script: |
    kubectl create secret docker-registry temp-secret-$APP_NAME \
      --docker-server=$CI_REGISTRY \
      --docker-username=gitlab-ci-token \
      --docker-password=$CI_BUILD_TOKEN
    export PULL_SECRET=$(kubectl get secrets temp-secret-$APP_NAME -o jsonpath="{.data['\.dockerconfigjson']}")
    kubectl delete secrets temp-secret-$APP_NAME
    
    helm upgrade --install $APP_NAME helm/$APP_NAME/ --values helm/$APP_NAME/values.yaml \
      --set imagePullSecrets=$PULL_SECRET \
      --set image.repository=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$APP_NAME:$CI_PIPELINE_ID \
      --set replicaCount=${REPLICAS} \
      --set RACK_ENV=${RACK_ENV} \
      --set REDIS_SERVER_ENDPOINT=${REDIS_SERVER_ENDPOINT} \
      --set YELB_DB_SERVER_ENDPOINT=${YELB_DB_SERVER_ENDPOINT} \
      --set ingress.hosts[0].host=$YC_BALANCER_IP.nip.io

.helm_delete:
  script:
    - helm uninstall $APP_NAME