{{- $imagePullSecrets := .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: temp-ui-{{ .Release.Name }}
data:
  .dockerconfigjson: {{ $imagePullSecrets }}
type: kubernetes.io/dockerconfigjson