appserver_build:
  stage: build
  extends:
    - .var_appserver
    - .build_command

appserver_deploy:
  stage: deploy
  extends:
    - .var_appserver
    - .yc_init
    - .helm_deploy
  needs: ['appserver_build']

appserver_delete:
  stage: delete
  extends:
    - .yc_init
    - .helm_delete
  when: manual

ui_build:
  stage: build
  extends:
    - .var_ui
    - .build_command

ui_deploy:
  stage: deploy
  extends:
    - .var_ui
    - .yc_init
    - .helm_deploy
  needs: ['ui_build']
  
ui_delete:
  stage: delete
  extends:
    - .yc_init
    - .helm_delete
  when: manual