appserver_helm_lint:
  stage: helm_lint
  extends:
    - .var_appserver
    - .helm_lint

ui_helm_lint:
  stage: helm_lint
  extends:
    - .var_ui
    - .helm_lint

appserver_build:
  stage: build
  extends:
    - .var_appserver
    - .build_command

ui_build:
  stage: build
  extends:
    - .var_ui
    - .build_command

appserver_deploy:
  stage: deploy
  extends:
    - .var_appserver
    - .yc_init
    - .helm_deploy

ui_deploy:
  stage: deploy
  extends:
    - .var_ui
    - .yc_init
    - .helm_deploy

appserver_delete:
  stage: delete
  extends:
    - .yc_init
    - .helm_delete
  when: manual
  
ui_delete:
  stage: delete
  extends:
    - .yc_init
    - .helm_delete
  when: manual